import { generatePersistentReferralCode, sanitizeReferralCode } from '@otp/domain';

const STORAGE_PREFIX = 'otp.referral-code.v1:';

type StorageLike = Pick<Storage, 'getItem' | 'setItem'>;

function defaultStorage(): StorageLike | null {
  try {
    return typeof window !== 'undefined' && window.localStorage ? window.localStorage : null;
  } catch {
    return null;
  }
}

/**
 * Returns the referral code for an identifier, keeping it stable across reloads on this device.
 * Codes are CSPRNG-generated by the domain helper; the identifier is only used as a lookup key
 * and never influences the code itself.
 */
export function resolveReferralCode(identifier: string, storage: StorageLike | null = defaultStorage()): string {
  const key = `${STORAGE_PREFIX}${identifier}`;
  if (storage) {
    try {
      const stored = storage.getItem(key);
      if (stored && /^[A-Z0-9]{2,6}-[A-Z0-9]{4,12}$/.test(stored) && sanitizeReferralCode(stored) === stored) {
        return stored;
      }
    } catch {
      // storage unavailable (private mode / quota); fall through to in-memory generation
    }
  }

  const code = generatePersistentReferralCode(identifier, 'OTP');
  if (storage) {
    try {
      storage.setItem(key, code);
    } catch {
      // best effort only
    }
  }
  return code;
}
